chapter \<open>Generated by Lem from \<open>/home/vogtb/theorem_stuff/sail-riscv/handwritten_support/riscv_extras_fdext.lem\<close>.\<close>

theory "Riscv_extras_fdext" 

imports
  Main
  "LEM.Lem_pervasives"
  "LEM.Lem_pervasives_extra"
  "Sail.Sail2_instr_kinds"
  "Sail.Sail2_values"

begin 

\<comment> \<open>\<open>=======================================================================================\<close>\<close>
\<comment> \<open>\<open>  This Sail RISC-V architecture model, comprising all files and                        \<close>\<close>
\<comment> \<open>\<open>  directories except where otherwise noted is subject the BSD                          \<close>\<close>
\<comment> \<open>\<open>  two-clause license in the LICENSE file.                                              \<close>\<close>
\<comment> \<open>\<open>                                                                                       \<close>\<close>
\<comment> \<open>\<open>  SPDX-License-Identifier: BSD-2-Clause                                                \<close>\<close>
\<comment> \<open>\<open>=======================================================================================\<close>\<close>

\<comment> \<open>\<open>open import Pervasives\<close>\<close>
\<comment> \<open>\<open>open import Pervasives_extra\<close>\<close>
\<comment> \<open>\<open>open import Sail2_instr_kinds\<close>\<close>
\<comment> \<open>\<open>open import Sail2_values\<close>\<close>

type_synonym bitvector0 =" Sail2_values.bitU list "

\<comment> \<open>\<open> stub functions emulating the C softfloat interface \<close>\<close>

\<comment> \<open>\<open>val softfloat_f16_round_to_int : bitvector -> bitvector -> bool -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f16_round_to_int  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bool \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f16_round_to_int _ _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_round_to_int : bitvector -> bitvector -> bool -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f32_round_to_int  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bool \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f32_round_to_int _ _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f64_round_to_int : bitvector -> bitvector -> bool -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f64_round_to_int  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bool \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f64_round_to_int _ _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f16_add : bitvector -> bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f16_add  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f16_add _ _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f16_sub : bitvector -> bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f16_sub  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f16_sub _ _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f16_mul : bitvector -> bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f16_mul  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f16_mul _ _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f16_div : bitvector -> bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f16_div  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f16_div _ _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_add : bitvector -> bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f32_add  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f32_add _ _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_sub : bitvector -> bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f32_sub  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f32_sub _ _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_mul : bitvector -> bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f32_mul  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f32_mul _ _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_div : bitvector -> bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f32_div  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f32_div _ _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f64_add : bitvector -> bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f64_add  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f64_add _ _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f64_sub : bitvector -> bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f64_sub  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f64_sub _ _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f64_mul : bitvector -> bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f64_mul  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f64_mul _ _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f64_div : bitvector -> bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f64_div  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f64_div _ _ _ = ( fail )\<close>



\<comment> \<open>\<open>val softfloat_f16_muladd : bitvector -> bitvector -> bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f16_muladd  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f16_muladd _ _ _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_muladd : bitvector -> bitvector -> bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f32_muladd  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f32_muladd _ _ _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f64_muladd : bitvector -> bitvector -> bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f64_muladd  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f64_muladd _ _ _ _ = ( fail )\<close>



\<comment> \<open>\<open>val softfloat_f16_sqrt : bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f16_sqrt  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f16_sqrt _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_sqrt : bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f32_sqrt  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f32_sqrt _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f64_sqrt : bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f64_sqrt  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f64_sqrt _ _ = ( fail )\<close>



\<comment> \<open>\<open>val softfloat_f16_to_i32: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f16_to_i32  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f16_to_i32 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f16_to_ui32: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f16_to_ui32  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f16_to_ui32 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_i32_to_f16: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_i32_to_f16  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_i32_to_f16 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_ui32_to_f16: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_ui32_to_f16  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_ui32_to_f16 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f16_to_i64: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f16_to_i64  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f16_to_i64 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f16_to_ui64: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f16_to_ui64  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f16_to_ui64 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_i64_to_f16: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_i64_to_f16  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_i64_to_f16 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_ui64_to_f16: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_ui64_to_f16  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_ui64_to_f16 _ _ = ( fail )\<close>



\<comment> \<open>\<open>val softfloat_f32_to_i32: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f32_to_i32  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f32_to_i32 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_to_ui32: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f32_to_ui32  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f32_to_ui32 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_i32_to_f32: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_i32_to_f32  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_i32_to_f32 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_ui32_to_f32: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_ui32_to_f32  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_ui32_to_f32 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_to_i64: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f32_to_i64  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f32_to_i64 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_to_ui64: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f32_to_ui64  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f32_to_ui64 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_i64_to_f32: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_i64_to_f32  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_i64_to_f32 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_ui64_to_f32: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_ui64_to_f32  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_ui64_to_f32 _ _ = ( fail )\<close>



\<comment> \<open>\<open>val softfloat_f64_to_i32: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f64_to_i32  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f64_to_i32 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f64_to_ui32: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f64_to_ui32  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f64_to_ui32 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_i32_to_f64: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_i32_to_f64  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_i32_to_f64 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_ui32_to_f64: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_ui32_to_f64  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_ui32_to_f64 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f64_to_i64: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f64_to_i64  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f64_to_i64 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f64_to_ui64: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f64_to_ui64  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f64_to_ui64 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_i64_to_f64: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_i64_to_f64  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_i64_to_f64 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_ui64_to_f64: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_ui64_to_f64  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_ui64_to_f64 _ _ = ( fail )\<close>



\<comment> \<open>\<open>val softfloat_f16_to_f32: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f16_to_f32  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f16_to_f32 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f16_to_f64: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f16_to_f64  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f16_to_f64 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_to_f64: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f32_to_f64  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f32_to_f64 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_to_f16: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f32_to_f16  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f32_to_f16 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f64_to_f16: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f64_to_f16  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f64_to_f16 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f64_to_f32: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f64_to_f32  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f64_to_f32 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_to_bf16: bitvector -> bitvector -> (bitvector * bitvector)\<close>\<close>
definition softfloat_f32_to_bf16  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bitvector0 \<close>  where 
     \<open> softfloat_f32_to_bf16 _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f16_lt : bitvector -> bitvector -> (bitvector * bool)\<close>\<close>
definition softfloat_f16_lt  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bool \<close>  where 
     \<open> softfloat_f16_lt _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f16_lt_quiet : bitvector -> bitvector -> (bitvector * bool)\<close>\<close>
definition softfloat_f16_lt_quiet  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bool \<close>  where 
     \<open> softfloat_f16_lt_quiet _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f16_le : bitvector -> bitvector -> (bitvector * bool)\<close>\<close>
definition softfloat_f16_le  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bool \<close>  where 
     \<open> softfloat_f16_le _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f16_le_quiet : bitvector -> bitvector -> (bitvector * bool)\<close>\<close>
definition softfloat_f16_le_quiet  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bool \<close>  where 
     \<open> softfloat_f16_le_quiet _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f16_eq : bitvector -> bitvector -> (bitvector * bool)\<close>\<close>
definition softfloat_f16_eq  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bool \<close>  where 
     \<open> softfloat_f16_eq _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_lt : bitvector -> bitvector -> (bitvector * bool)\<close>\<close>
definition softfloat_f32_lt  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bool \<close>  where 
     \<open> softfloat_f32_lt _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_lt_quiet : bitvector -> bitvector -> (bitvector * bool)\<close>\<close>
definition softfloat_f32_lt_quiet  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bool \<close>  where 
     \<open> softfloat_f32_lt_quiet _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_le : bitvector -> bitvector -> (bitvector * bool)\<close>\<close>
definition softfloat_f32_le  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bool \<close>  where 
     \<open> softfloat_f32_le _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_le_quiet : bitvector -> bitvector -> (bitvector * bool)\<close>\<close>
definition softfloat_f32_le_quiet  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bool \<close>  where 
     \<open> softfloat_f32_le_quiet _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f32_eq : bitvector -> bitvector -> (bitvector * bool)\<close>\<close>
definition softfloat_f32_eq  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bool \<close>  where 
     \<open> softfloat_f32_eq _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f64_lt : bitvector -> bitvector -> (bitvector * bool)\<close>\<close>
definition softfloat_f64_lt  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bool \<close>  where 
     \<open> softfloat_f64_lt _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f64_lt_quiet : bitvector -> bitvector -> (bitvector * bool)\<close>\<close>
definition softfloat_f64_lt_quiet  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bool \<close>  where 
     \<open> softfloat_f64_lt_quiet _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f64_le : bitvector -> bitvector -> (bitvector * bool)\<close>\<close>
definition softfloat_f64_le  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bool \<close>  where 
     \<open> softfloat_f64_le _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f64_le_quiet : bitvector -> bitvector -> (bitvector * bool)\<close>\<close>
definition softfloat_f64_le_quiet  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bool \<close>  where 
     \<open> softfloat_f64_le_quiet _ _ = ( fail )\<close>


\<comment> \<open>\<open>val softfloat_f64_eq : bitvector -> bitvector -> (bitvector * bool)\<close>\<close>
definition softfloat_f64_eq  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow> bitvector0*bool \<close>  where 
     \<open> softfloat_f64_eq _ _ = ( fail )\<close>

end
