chapter \<open>Generated by Lem from \<open>/home/vogtb/theorem_stuff/sail-riscv/handwritten_support/riscv_extras.lem\<close>.\<close>

theory "Riscv_extras" 

imports
  Main
  "LEM.Lem_pervasives"
  "LEM.Lem_pervasives_extra"
  "Sail.Sail2_instr_kinds"
  "Sail.Sail2_values"
  "Sail.Sail2_operators_bitlists"
  "Sail.Sail2_concurrency_interface"
  "Sail.Sail2_monadic_combinators"
  "Sail.Sail2_undefined_concurrency_interface"

begin 

\<comment> \<open>\<open>=======================================================================================\<close>\<close>
\<comment> \<open>\<open>  This Sail RISC-V architecture model, comprising all files and                        \<close>\<close>
\<comment> \<open>\<open>  directories except where otherwise noted is subject the BSD                          \<close>\<close>
\<comment> \<open>\<open>  two-clause license in the LICENSE file.                                              \<close>\<close>
\<comment> \<open>\<open>                                                                                       \<close>\<close>
\<comment> \<open>\<open>  SPDX-License-Identifier: BSD-2-Clause                                                \<close>\<close>
\<comment> \<open>\<open>=======================================================================================\<close>\<close>

\<comment> \<open>\<open>open import Pervasives\<close>\<close>
\<comment> \<open>\<open>open import Pervasives_extra\<close>\<close>
\<comment> \<open>\<open>open import Sail2_instr_kinds\<close>\<close>
\<comment> \<open>\<open>open import Sail2_values\<close>\<close>
\<comment> \<open>\<open>open import Sail2_operators_bitlists\<close>\<close>
\<comment> \<open>\<open>open import Sail2_concurrency_interface\<close>\<close>
\<comment> \<open>\<open>open import Sail2_monadic_combinators\<close>\<close>
\<comment> \<open>\<open>open import Sail2_undefined_concurrency_interface\<close>\<close>

type_synonym bitvector =" Sail2_values.bitU list "

\<comment> \<open>\<open>val load_reservation : forall 'abort 'barrier 'cache_op 'fault 'pa 'tlb_op 'translation_summary 'trans_start 'trans_end 'arch_ak 'rv 'e. bitvector -> integer -> monad 'abort 'barrier 'cache_op 'fault 'pa 'tlb_op 'translation_summary 'trans_start 'trans_end 'arch_ak 'rv unit 'e\<close>\<close>
definition load_reservation  :: \<open>(bitU)list \<Rightarrow> int \<Rightarrow>('abort,'barrier,'cache_op,'fault,'pa,'tlb_op,'translation_summary,'trans_start,'trans_end,'arch_ak,'rv,(unit),'e)monad \<close>  where 
     \<open> load_reservation addr width = ( return ()  )\<close> 
  for  "addr"  :: "(bitU)list " 
  and  "width"  :: " int "


definition match_reservation  :: \<open> 'a \<Rightarrow> bool \<close>  where 
     \<open> match_reservation _ = ( True )\<close>

definition cancel_reservation  :: \<open> unit \<Rightarrow>('l,'k,'j,'i,'h,'g,'f,'e,'d,'c,'b,(unit),'a)monad \<close>  where 
     \<open> cancel_reservation _ = ( return ()  )\<close>

definition valid_reservation  :: \<open> unit \<Rightarrow> bool \<close>  where 
     \<open> valid_reservation _ = ( False )\<close>


\<comment> \<open>\<open>val plat_term_write : forall 'abort 'barrier 'cache_op 'fault 'pa 'tlb_op 'translation_summary 'trans_start 'trans_end 'arch_ak 'rv 'e. bitvector -> monad 'abort 'barrier 'cache_op 'fault 'pa 'tlb_op 'translation_summary 'trans_start 'trans_end 'arch_ak 'rv unit 'e\<close>\<close>
definition plat_term_write  :: \<open>(bitU)list \<Rightarrow>('abort,'barrier,'cache_op,'fault,'pa,'tlb_op,'translation_summary,'trans_start,'trans_end,'arch_ak,'rv,(unit),'e)monad \<close>  where 
     \<open> plat_term_write _ = ( return ()  )\<close>


\<comment> \<open>\<open>val plat_term_read : forall 'abort 'barrier 'cache_op 'fault 'pa 'tlb_op 'translation_summary 'trans_start 'trans_end 'arch_ak 'rv 'e. unit -> monad 'abort 'barrier 'cache_op 'fault 'pa 'tlb_op 'translation_summary 'trans_start 'trans_end 'arch_ak 'rv bitvector 'e\<close>\<close>
definition plat_term_read  :: \<open> unit \<Rightarrow>('abort,'barrier,'cache_op,'fault,'pa,'tlb_op,'translation_summary,'trans_start,'trans_end,'arch_ak,'rv,((bitU)list),'e)monad \<close>  where 
     \<open> plat_term_read _ = ( return [])\<close>


definition plat_get_16_random_bits  :: \<open> 'b Bitvector_class \<Rightarrow> 'c Register_Value_class \<Rightarrow> unit \<Rightarrow>('m,'l,'k,'j,'i,'h,'g,'f,'e,'d,'c,'b,'a)monad \<close>  where 
     \<open> plat_get_16_random_bits dict_Sail2_values_Bitvector_b dict_Sail2_values_Register_Value_c _ = ( undefined_bitvector 
  dict_Sail2_values_Bitvector_b dict_Sail2_values_Register_Value_c(( 16 :: int)))\<close> 
  for  "dict_Sail2_values_Bitvector_b"  :: " 'b Bitvector_class " 
  and  "dict_Sail2_values_Register_Value_c"  :: " 'c Register_Value_class "


definition sys_enable_experimental_extensions  :: \<open> unit \<Rightarrow> bool \<close>  where 
     \<open> sys_enable_experimental_extensions _ = ( False )\<close>


\<comment> \<open>\<open>val shift_bits_right : bitvector -> bitvector -> bitvector\<close>\<close>
definition shift_bits_right  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<close>  where 
     \<open> shift_bits_right v m = ( shiftr v (uint0 m))\<close> 
  for  "v"  :: "(bitU)list " 
  and  "m"  :: "(bitU)list "

\<comment> \<open>\<open>val shift_bits_left : bitvector -> bitvector -> bitvector\<close>\<close>
definition shift_bits_left  :: \<open>(bitU)list \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<close>  where 
     \<open> shift_bits_left v m = ( shiftl v (uint0 m))\<close> 
  for  "v"  :: "(bitU)list " 
  and  "m"  :: "(bitU)list "


\<comment> \<open>\<open>val print_string : string -> string -> unit\<close>\<close>
definition print_string  :: \<open> string \<Rightarrow> string \<Rightarrow> unit \<close>  where 
     \<open> print_string msg s = ( ()  )\<close> 
  for  "msg"  :: " string " 
  and  "s"  :: " string "
 \<comment> \<open>\<open> print_endline (msg ^ s) \<close>\<close>

\<comment> \<open>\<open>val prerr_string : string -> string -> unit\<close>\<close>
definition prerr_string  :: \<open> string \<Rightarrow> string \<Rightarrow> unit \<close>  where 
     \<open> prerr_string msg s = ( prerr_endline (msg @ s))\<close> 
  for  "msg"  :: " string " 
  and  "s"  :: " string "


\<comment> \<open>\<open>val prerr_bits : string -> bitvector -> unit\<close>\<close>
definition prerr_bits0  :: \<open> string \<Rightarrow>(bitU)list \<Rightarrow> unit \<close>  where 
     \<open> prerr_bits0 msg bs = ( prerr_endline (msg @ (show_bitlist (List.map ((\<lambda> b. b)) bs))))\<close> 
  for  "msg"  :: " string " 
  and  "bs"  :: "(bitU)list "


\<comment> \<open>\<open>val print_bits : string -> bitvector -> unit\<close>\<close>
definition print_bits0  :: \<open> string \<Rightarrow>(bitU)list \<Rightarrow> unit \<close>  where 
     \<open> print_bits0 msg bs = ( print_endline (msg @ (show_bitlist (List.map ((\<lambda> b. b)) bs))))\<close> 
  for  "msg"  :: " string " 
  and  "bs"  :: "(bitU)list "


\<comment> \<open>\<open>val print_dbg : string -> unit\<close>\<close>
definition print_dbg  :: \<open> string \<Rightarrow> unit \<close>  where 
     \<open> print_dbg msg = ( ()  )\<close> 
  for  "msg"  :: " string "

end
